module_enable_status:
  blc: True
  awb: True
  cfa: True
  ccm: True
  gac: True
  csc: True
  nlm: True        # noise processing (after demosaic)
  eeh: True        # edge enhancement
  

hardware:
  raw_width: 3000
  raw_height: 2000
  raw_bit_depth: 14
  bayer_pattern: rggb

# -------------------- Module Algorithms Parameters --------------------

blc:
  bl_r: 64                         # sensor black level (approx for 10-bit)
  bl_gr: 64
  bl_gb: 64
  bl_b: 64
  alpha: 0
  beta: 0

cfa:
  mode: malvar                     # higher quality demosaic

awb:
  r_gain: &r_gain 2415                # x1024
  gr_gain: 1024                       # x1024
  gb_gain: 1024                       # x1024
  b_gain: &b_gain 1168                    # boosts blue relative to green

ccm:
  ccm:
    - [ 1670, -508, -139, 0 ]      # approx from dcraw
    - [  -20, 1404, -360, 0 ]
    - [   58, -406, 1372, 0 ]

nlm:
  search_window_size: 7
  patch_size: 3
  h: 12                            # smoothing strength

eeh:
  edge_gain: 384                   # sharpening factor (~1.5×)
  flat_threshold: 4
  edge_threshold: 8
  delta_threshold: 64

gac:
  gain: 256
  gamma: 0.45                      # sRGB-like gamma
